### ISSUE TITLE
Ajustar Planejamento

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.2-Dubium#1]
Na coluna de produto está sendo registrado atividades e produtos. Devem estar apenas os produtos.
A equipe não estão fazendo mais nada no projeto a não ser definição de escopo? instalação de ambiente, testes de ambiente, estudo de tecnologia, provas de conceitos, configuração de CI/CD?

**Comment by alcantaragiubs** [comment]
Será adicionado o resto das coisas que a equipe está fazendo. Nesse momento de entrega da Unidade 1, colocamos apenas as coisas que já fizemos e as datas referentes as entregas finais.

**Comment by alcantaragiubs** [comment]
Corrigido e sera subido para o pages
