### ISSUE TITLE
Matriz de Comunicação

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.2-Dubium#2]
Vcs vão fazer relatórios diários?!
Onde vão postar eles, no GitPages?!

<html>
<body>

Daily | Equipe do Projeto | Diário | **Relatório da daily**, **Relatório de situação do projeto**, Atualização sobre o andamento do projeto
-- | -- | -- | --

</body>
</html>

**Comment by alcantaragiubs** [comment]
Corrigi isso no documento e em breve a mudança será subida para o gitpages. Sim, serão feitos pequenos relatórios diários via telegram sobre a participação de cada um no projeto e quais passos foram evoluídos no dia. Semanalmente, atualizaremos o pages com todos os relatórios das dailys que duraram naquela sprint.

**Comment by alcantaragiubs** [comment]
Corrigido e sera passado para o pages em breve
