### ISSUE TITLE
Atividades e Ciclo de Vida

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.2-Dubium#4]
Existem várias informações soltas que não se comunicam.

- [x] É preciso posicionar as atividades dentro do ciclo de vida que será utilizado pelo projeto.
- [x] As atividades de ANÁLISE DE REQUISITOS, DOCUMENTAÇÃO DE REQUISITOS, VERIFICAÇÃO E VALIDAÇÃO DE REQUISITOS, GERENCIAMENTO DE REQUISITOS não possuem nenhuma descrição.
- [x] não há nenhuma descrição das atividades de implementação: codificação - modelagem de banco de dados, programação back-end e front-end, criação de cenários de testes
- [x] Backlog do Produto e da Sprint, são artefatos. Em que atividades serão feitos?
- [x] Review, qual o resultado dessa atividade?
- [x] Retrospectiva, qual o resultado dessa atividade?
- [x] Entrega, em qual atividade será feita?

**Comment by alcantaragiubs** [comment]
Atualizado e subido para o pages
